import { type NextPage } from 'next'
import Head from 'next/head'
import tw from 'twin.macro'
import { Button, Logo } from '~/components'
import { api } from '~/utils/api'

const styles = {
  // Move long class sets out of jsx to keep it scannable
  container: ({ hasBackground }: { hasBackground: boolean }) => [
    tw`flex flex-col items-center justify-center h-screen`,
    hasBackground && tw`bg-gradient-to-b from-electric to-ribbon`,
  ],
}

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: 'from twin!' })

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div css={styles.container({ hasBackground: true })}>
        <div tw="flex flex-col justify-center h-full gap-y-5">
          <Button $variant="primary">Submit</Button>
          <Button $variant="secondary">Cancel</Button>
          <Button $isSmall>Close</Button>
          <p className="text-2xl text-white text-center w-full">
            {hello.data ? hello.data.greeting : 'Loading...'}
          </p>
        </div>
        <Logo />
      </div>
    </>
  )
}

export default Home
